services:
  - type: web
    name: corporate-intel-api
    env: docker
    plan: free
    region: singapore # You can change this to ohio, frankfurt, etc.
    branch: main
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: API_SECRET_KEY
        sync: false